services:
    app:
        build:
            context: ./docker
        tty: true
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
        volumes:
            - ${PWD}/docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app
    node:
        image: node:23-alpine
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ${PWD}/docker/scripts/node.sh:/bin/node/entrypoint.sh
        ports:
            - 5173:5173
        entrypoint: /bin/node/entrypoint.sh
    db:
        image: mysql:8.0.40-bookworm
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: brainstation
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
